[tool.black]
line-length = 100
target-version = ['py39'] 
include = '\.pyi?$'  

[tool.black.exclude]
paths = [
    "fastapi_env",    # Exclude virtual environment directory
    ".venv",          # Exclude hidden virtual environment directory
    "tests",         # Exclude tests directory
    "migration",     # Exclude migration directory
]

[tool.black.ignore]
# Add specific files or directories to ignore formatting
files = [
    "__init__.py"
]

